IF NOT DEFINED PROG_FOLDER EXIT /B
:FILE_MANAGEMENT
CLS&&CALL "%MODULE_FOLDER%\PADLINE.CMD"&&SET "$BOX=RT"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"
ECHO.                            File Management&&ECHO.
IF NOT DEFINED FMGR_DUAL SET "FMGR_DUAL=DISABLED"
IF NOT DEFINED FMGR_SOURCE SET "FMGR_SOURCE=%PROG_FOLDER%"&&SET "FMGR_TARGET=%PROG_FOLDER%"
IF NOT EXIST "%FMGR_SOURCE%\*" SET "FMGR_SOURCE=%PROG_FOLDER%"&&SET "FMGR_TARGET=%PROG_FOLDER%"
IF "%FMGR_DUAL%"=="ENABLED" ECHO.                           %@@%SOURCE%$$% (%##%X%$$%) %@@%TARGET%$$%&&ECHO.&&ECHO.  %@@%TARGET FOLDER:%$$% %FMGR_TARGET%&&ECHO.&&SET "$FOLD=%FMGR_TARGET%"&&SET "$FILT=*.*"&&SET "$DISP=BAS"&&CALL "%MODULE_FOLDER%\FILELIST.CMD"
ECHO.&&ECHO.  %@@%SOURCE FOLDER:%$$% %FMGR_SOURCE%&&ECHO.&&ECHO.  (%##%..%$$%)&&SET "$FOLD=%FMGR_SOURCE%"&&SET "$FILT=*.*"&&SET "$DISP=BAS"&&CALL "%MODULE_FOLDER%\FILELIST.CMD"&&ECHO.&&SET "$BOX=RB"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&CALL "%MODULE_FOLDER%\PADLINE.CMD"
ECHO. (%##%E%$$%)xplore (%##%N%$$%)ew (%##%O%$$%)pen (%##%C%$$%)opy (%##%M%$$%)ove (%##%R%$$%)ename (%##%D%$$%)elete (%##%#%$$%)Own (%##%V%$$%)iew
CALL "%MODULE_FOLDER%\PADLINE.CMD"&&ECHO.               Press (%##%Enter%$$%) to return to previous menu&&CALL "%MODULE_FOLDER%\MENUSELECT.CMD"
IF NOT DEFINED SELECT EXIT /B
IF "%SELECT%"=="X" CALL:FMGR_SWAP&SET "SELECT="
IF "%SELECT%"=="E" CALL:FMGR_EXPLORE&SET "SELECT="
IF "%SELECT%"=="N" CALL:FMGR_NEW&SET "SELECT="
IF "%SELECT%"=="V" IF "%FMGR_DUAL%"=="DISABLED" SET "FMGR_DUAL=ENABLED"&SET "SELECT="
IF "%SELECT%"=="V" IF "%FMGR_DUAL%"=="ENABLED" SET "FMGR_DUAL=DISABLED"&SET "SELECT="
IF "%SELECT%"=="C" SET "$FOLD=%FMGR_SOURCE%"&&SET "$FILT=*.*"&&CALL:FILE_PROMPT&&CALL:FMGR_COPY&SET "SELECT="
IF "%SELECT%"=="O" SET "$FOLD=%FMGR_SOURCE%"&&SET "$FILT=*.*"&&CALL:FILE_PROMPT&&CALL:FMGR_OPEN&SET "SELECT="
IF "%SELECT%"=="M" SET "$FOLD=%FMGR_SOURCE%"&&SET "$FILT=*.*"&&CALL:FILE_PROMPT&&CALL:FMGR_MOVE&SET "SELECT="
IF "%SELECT%"=="R" SET "$FOLD=%FMGR_SOURCE%"&&SET "$FILT=*.*"&&CALL:FILE_PROMPT&&CALL:FMGR_REN&SET "SELECT="
IF "%SELECT%"=="#" SET "$FOLD=%FMGR_SOURCE%"&&SET "$FILT=*.*"&&CALL:FILE_PROMPT&&CALL:FMGR_OWN&SET "SELECT="
IF "%SELECT%"=="D" SET "$FOLD=%FMGR_SOURCE%"&&SET "$FILT=*.*"&&CALL:FILE_PROMPT&&CALL:FMGR_DEL&SET "SELECT="
IF "%SELECT%"==".." CALL SET "FMGR_SOURCE=%%FMGR_SOURCE_%FMS#%%%"&&CALL SET /A "FMS#-=1"
GOTO:FILE_MANAGEMENT
:FILE_PROMPT
CALL "%MODULE_FOLDER%\PADLINE.CMD"&&SET "$BOX=RT"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&ECHO.  %@@%FOLDER CONTENTS:%$$%&&ECHO.&&CALL "%MODULE_FOLDER%\FILELIST.CMD"&&ECHO.&&SET "$BOX=RB"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&CALL "%MODULE_FOLDER%\PADLINE.CMD"&&ECHO.               Press (%##%Enter%$$%) to return to previous menu&&CALL "%MODULE_FOLDER%\MENUSELECT.CMD"
EXIT /B
:FMGR_NEW
CLS&&CALL "%MODULE_FOLDER%\PADLINE.CMD"&&SET "$BOX=RT"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&ECHO.                           Create which type&&ECHO.&&ECHO. (%##%1%$$%) Folder&&ECHO. (%##%2%$$%) File&&ECHO.&&SET "$BOX=RB"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&CALL "%MODULE_FOLDER%\PADLINE.CMD"&&ECHO.               Press (%##%Enter%$$%) to return to previous menu&&SET "$SELECT=NEW_TYPE"&&CALL "%MODULE_FOLDER%\MENUSELECT.CMD"
IF NOT "%NEW_TYPE%"=="1" IF NOT "%NEW_TYPE%"=="2" EXIT /B
IF "%NEW_TYPE%"=="1" CALL "%MODULE_FOLDER%\PADLINE.CMD"&&SET "$BOX=RT"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&ECHO.&&ECHO.                         Enter new folder name&&ECHO.&&SET "$BOX=RB"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&CALL "%MODULE_FOLDER%\PADLINE.CMD"&&ECHO.               Press (%##%Enter%$$%) to return to previous menu&&SET "$SELECT=NEW_NAME"&&SET "$CASE=ANY"&&SET "NO_ASTRK=1"&&CALL "%MODULE_FOLDER%\MENUSELECT.CMD"
IF "%NEW_TYPE%"=="1" IF NOT DEFINED NEW_NAME EXIT /B
IF "%NEW_TYPE%"=="1" SET "NEW_TYPE="&&MD "%FMGR_SOURCE%\%NEW_NAME%">NUL 2>&1
IF "%NEW_TYPE%"=="2" CALL "%MODULE_FOLDER%\PADLINE.CMD"&&SET "$BOX=RT"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&ECHO.&&ECHO.                Enter new file name including extension&&ECHO.&&SET "$BOX=RB"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&CALL "%MODULE_FOLDER%\PADLINE.CMD"&&ECHO.               Press (%##%Enter%$$%) to return to previous menu&&SET "$SELECT=NEW_NAME"&&SET "$CASE=ANY"&&SET "NO_ASTRK=1"&&CALL "%MODULE_FOLDER%\MENUSELECT.CMD"
IF "%NEW_TYPE%"=="2" IF NOT DEFINED NEW_NAME EXIT /B
IF "%NEW_TYPE%"=="2" SET "NEW_TYPE="&&ECHO.>"%FMGR_SOURCE%\%NEW_NAME%"
EXIT /B
:FMGR_REN
IF NOT DEFINED $PICK EXIT /B
CALL "%MODULE_FOLDER%\PADLINE.CMD"&&SET "$BOX=RT"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&ECHO.&&IF EXIST "%$PICK%\*" ECHO.                         Enter new folder name
IF NOT EXIST "%$PICK%\*" ECHO.                Enter new file name including extension
ECHO.&&SET "$BOX=RB"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&CALL "%MODULE_FOLDER%\PADLINE.CMD"&&ECHO.               Press (%##%Enter%$$%) to return to previous menu&&SET "$SELECT=NEW_NAME"&&SET "$CASE=ANY"&&SET "NO_ASTRK=1"&&CALL "%MODULE_FOLDER%\MENUSELECT.CMD"
IF NOT DEFINED NEW_NAME EXIT /B
ECHO. Renaming %@@%%$PICK%%$$% to %@@%%FMGR_SOURCE%\%NEW_NAME%%$$%.
REN "%$PICK%" "%NEW_NAME%"
EXIT /B
:FMGR_DEL
IF NOT DEFINED $PICK EXIT /B
IF NOT EXIST "%$PICK%\*" DEL /Q /F "\\?\%$PICK%"
IF EXIST "%$PICK%\*" RD /S /Q "\\?\%$PICK%"
IF NOT EXIST "%$PICK%\*" IF NOT EXIST "%$PICK%" ECHO. Deleting %@@%%$PICK%%$$%.
EXIT /B
:FMGR_OPEN
IF NOT DEFINED $PICK EXIT /B
IF NOT EXIST "%$PICK%\*" "%$PICK%"&EXIT /B
IF EXIST "%$PICK%\*" CALL SET /A "FMS#+=1"
CALL SET "FMGR_SOURCE_%FMS#%=%FMGR_SOURCE%"&&CALL SET "FMGR_SOURCE=%$PICK%"
EXIT /B
:FMGR_COPY
IF NOT DEFINED $PICK EXIT /B
IF "%FMGR_SOURCE%"=="%FMGR_TARGET%" CALL:FMGR_SAME&EXIT /B
IF NOT EXIST "%$PICK%\*" ECHO.Copying %@@%%$PICK%%$$% to %@@%%FMGR_TARGET%%$$%...&&XCOPY "%$PICK%" "%FMGR_TARGET%" /C /Y>NUL 2>&1
IF EXIST "%$PICK%\*" ECHO.Copying %@@%%$PICK%%$$% to %@@%%FMGR_TARGET%%$$%...&&XCOPY "%$PICK%" "%FMGR_TARGET%\%$CHOICE%\" /E /C /I /Y>NUL 2>&1
EXIT /B
:FMGR_SYM
IF NOT DEFINED $PICK EXIT /B
IF "%FMGR_SOURCE%"=="%FMGR_TARGET%" CALL:FMGR_SAME&EXIT /B
IF EXIST "%$PICK%\*" MKLINK /J "%FMGR_TARGET%\%$CHOICE%" "%$PICK%"
IF NOT EXIST "%$PICK%\*" MKLINK "%FMGR_TARGET%\%$CHOICE%" "%$PICK%"
EXIT /B
:FMGR_MOVE
IF NOT DEFINED $PICK EXIT /B
IF "%FMGR_SOURCE%"=="%FMGR_TARGET%" CALL:FMGR_SAME&EXIT /B
IF NOT EXIST "%$PICK%\*" ECHO.Moving %@@%%$PICK%%$$% to %@@%%FMGR_TARGET%%$$%...&&MOVE /Y "%$PICK%" "%FMGR_TARGET%">NUL 2>&1
IF EXIST "%$PICK%\*" ECHO.Moving %@@%%$PICK%%$$% to %@@%%FMGR_TARGET%%$$%...&&XCOPY "%$PICK%" "%FMGR_TARGET%\%$CHOICE%\" /E /C /I /Y>NUL 2>&1
IF EXIST "%$PICK%\*" RD /S /Q "\\?\%$PICK%">NUL 2>&1
EXIT /B
:FMGR_OWN
IF NOT DEFINED $PICK EXIT /B
IF NOT DEFINED NO_PAUSE CALL "%MODULE_FOLDER%\PADLINE.CMD"&&SET "$BOX=RT"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&ECHO.
IF NOT EXIST "%$PICK%\*" TAKEOWN /F "%$PICK%"
IF NOT EXIST "%$PICK%\*" ICACLS "%$PICK%" /grant %USERNAME%:F >NUL 2>&1
IF EXIST "%$PICK%\*" TAKEOWN /F "%$PICK%" /R /D Y
IF EXIST "%$PICK%\*" ICACLS "%$PICK%" /grant %USERNAME%:F /T >NUL 2>&1
ECHO.&&IF NOT DEFINED NO_PAUSE ECHO.&&SET "$BOX=RB"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&CALL "%MODULE_FOLDER%\PADLINE.CMD"
PAUSE
EXIT /B
:FMGR_EXPLORE
CLS&&CALL "%MODULE_FOLDER%\PADLINE.CMD"&&SET "$BOX=RT"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&ECHO.                       Enter the PATH to explore&&ECHO.&&ECHO.  %@@%AVAILABLE PATHs:%$$%&&ECHO.&&FOR %%G in (A B C D E F G H I J K L M N O P Q R S T U V W X Y Z) DO (IF EXIST "%%G:\" ECHO. ^( %##%%%G%$$% ^) Volume %%G:)
ECHO.&&SET "$BOX=RB"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&CALL "%MODULE_FOLDER%\PADLINE.CMD"&&ECHO.               Press (%##%Enter%$$%) to return to previous menu&&SET "$CHECK=MOST"&&SET "NO_ASTRK=1"&&CALL "%MODULE_FOLDER%\MENUSELECT.CMD"
IF DEFINED SELECT FOR %%G in (A B C D E F G H I J K L M N O P Q R S T U V W X Y Z) DO (IF "%SELECT%"=="%%G" IF EXIST "%%G:\" SET "FMGR_SOURCE=%SELECT%:"&&EXIT /B)
IF DEFINED SELECT SET "INPUT=%SELECT%"&&SET "OUTPUT=FMGR_SOURCE"&&CALL:SLASH
EXIT /B
:FMGR_SAME
CALL "%MODULE_FOLDER%\PADLINE.CMD"&&SET "$BOX=RT"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&ECHO.&&ECHO.                       Source/Target are the same..&&ECHO.&&SET "$BOX=RB"&&CALL "%MODULE_FOLDER%\BOXDISP.CMD"&&CALL "%MODULE_FOLDER%\PADLINE.CMD"&&PAUSE
EXIT /B
:FMGR_SWAP
IF NOT EXIST "%FMGR_SOURCE%" EXIT /B
IF NOT EXIST "%FMGR_TARGET%" EXIT /B
SET "FMGR_SOURCE=%FMGR_TARGET%"&&SET "FMGR_TARGET=%FMGR_SOURCE%"
EXIT /B
:SLASH
FOR /F "DELIMS=" %%G in ('CMD.EXE /D /U /C ECHO.%INPUT%^| FIND /V ""') do (SET "SLASH_X=%%G"&&CALL:SLASH_X)
IF NOT "%SLASH_X%"=="\" IF EXIST "%INPUT%\" SET "%OUTPUT%=%INPUT%"
IF "%SLASH_X%"=="\" IF EXIST "%INPUT%" SET "%OUTPUT%=%SLASH_Z%"
IF NOT EXIST "%INPUT%\" SET "%OUTPUT%="
FOR %%a in (SLASH_X SLASH_Y SLASH_Z OUTPUT INPUT) DO (SET "%%a=")
EXIT /B
:SLASH_X
SET "SLASH_Z=%SLASH_Y%"&&SET "SLASH_Y=%SLASH_Y%%SLASH_X%"
EXIT /B