:PROMPT_SET
IF NOT DEFINED PROG_FOLDER EXIT /B
IF NOT DEFINED CHECK SET "CHECK=MENU"
IF NOT DEFINED QUOTE SET "QUOTE=NONE"
IF NOT DEFINED PROMPT_SET SET "PROMPT_SET=SELECT"
SET "ERROR="&&SET "%PROMPT_SET%="&&SET "PROMPT_VAR="&&SET /P "PROMPT_VAR=$>>"
IF NOT DEFINED PROMPT_VAR SET "%PROMPT_SET%="&&GOTO:PROMPT_SET_END
IF "%QUOTE%"=="NONE" SET "PROMPT_VAR=%PROMPT_VAR:"=%"
SET "PROMPT_VAR=%PROMPT_VAR:&=^%"
SET "PROMPT_VAR=%PROMPT_VAR:|=^%"
SET "PROMPT_VAR=%PROMPT_VAR:!=^%"
SET "PROMPT_VAR=%PROMPT_VAR:;=^%"
IF "%QUOTE%"=="ALLOW" SET "INPUT=%PROMPT_VAR:"=""%"
IF "%QUOTE%"=="ALLOW" SET "OUTPUT=PROMPT_VAR"&&CALL:QUOTE
IF NOT DEFINED PROMPT_VAR SET "%PROMPT_SET%="&&GOTO:PROMPT_SET_END
IF NOT DEFINED ERROR IF NOT DEFINED PROMPT_VAR SET "ERROR=1"&&GOTO:PROMPT_SET_END
IF NOT DEFINED ERROR IF DEFINED CHECK SET "CHECK_VAR=%PROMPT_VAR%"&&CALL:CHECK
IF NOT DEFINED ERROR IF NOT DEFINED PROMPT_ANY SET "CAPS_SET=%PROMPT_SET%"&&SET "CAPS_VAR=%PROMPT_VAR%"&&CALL:CAPS_SET
IF NOT DEFINED ERROR IF DEFINED PROMPT_ANY SET "%PROMPT_SET%=%PROMPT_VAR%"
:PROMPT_SET_END
FOR %%a in (PROMPT_VAR %PROMPT_SET%) DO (IF NOT DEFINED %%a SET "ERROR=1")
IF "%PROMPT_VAR%"=="=" SET "ERROR=1"
IF DEFINED ERROR IF DEFINED VERBOSE FOR /F "TOKENS=*" %%a in ("%PROMPT_VAR% ") DO (ECHO. %XLR4%ERROR:%#$% input [ %XLR4%%%a%#$%] is invalid)
IF DEFINED ERROR SET "%PROMPT_SET%="
FOR %%a in (VERBOSE CHECK INPUT OUTPUT PROMPT_ANY PROMPT_SET PROMPT_VAR QUOTE) DO (SET "%%a=")
EXIT /B
:CHECK
SET "ERROR="&&IF NOT DEFINED CHECK_VAR SET "ERROR=1"
IF "%CHECK%"=="NUM" SET "CHECK_FLT=0 1 2 3 4 5 6 7 8 9 ^""
IF "%CHECK%"=="LTR" SET "CHECK_FLT=A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z ^""
IF "%CHECK%"=="ALPHA" SET "CHECK_FLT=0 1 2 3 4 5 6 7 8 9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z ^""
IF "%CHECK%"=="MENU" SET "CHECK_FLT=0 1 2 3 4 5 6 7 8 9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z @ # $ . - _ + = ~ ^* ^""
IF "%CHECK%"=="MOST" SET "CHECK_FLT=0 1 2 3 4 5 6 7 8 9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z @ # $ ^\ ^/ ^: ^( ^) ^[ ^] ^{ ^} ^. ^- ^_ ^+ ^= ^~ ^* ^%% ^""
IF NOT DEFINED ERROR FOR /F "DELIMS=" %%$ in ('CMD.EXE /D /U /C ECHO."%CHECK_VAR%"^| FIND /V ""') do (SET "$GO="&&FOR %%a in (%CHECK_FLT%) DO (
IF "[%%$]"=="[*]" IF NOT DEFINED NO_ASTRK SET "$GO=1"
IF "[%%$]"=="[ ]" IF NOT DEFINED NO_SPACE SET "$GO=1"
IF "[%%a]"=="[%%$]" SET "$GO=1")
IF NOT DEFINED $GO SET "ERROR=1")
FOR %%a in (CHECK INPUT OUTPUT CHECK_VAR CHECK_FLT NO_SPACE NO_ASTRK) DO (SET "%%a=")
EXIT /B
:CAPS_SET
IF NOT DEFINED CAPS_VAR SET "%CAPS_SET%="&&SET "CAPS_SET="&&SET "CAPS_VAR="&&SET "CASE="&&EXIT /B
IF NOT DEFINED CASE SET "CASE=UPPER"
IF "%CASE%"=="LOWER" FOR %%G in (a b c d e f g h i j k l m n o p q r s t u v w x y z) DO (CALL SET "CAPS_VAR=%%CAPS_VAR:%%G=%%G%%")
IF "%CASE%"=="UPPER" FOR %%G in (A B C D E F G H I J K L M N O P Q R S T U V W X Y Z) DO (CALL SET "CAPS_VAR=%%CAPS_VAR:%%G=%%G%%")
IF "%CAPS_VAR%"=="a=a" SET "CAPS_VAR="
IF "%CAPS_VAR%"=="A=A" SET "CAPS_VAR="
CALL SET "%CAPS_SET%=%CAPS_VAR%"&&SET "CAPS_SET="&&SET "CAPS_VAR="&&SET "CASE="
EXIT /B